version: "3"
services:
  app:
    container_name: sk-api
    restart: always
    build: .
    env_file: .env
    ports:
      - "9000:9000"
    links:
      - db
  db:
    container_name: sk-postgres
    image: timescale/timescaledb:2.0.0-pg12
    ports:
      - "5432:5432"